//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyShop.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int ID { get; set; }
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual AdminService AdminService { get; set; }
        public virtual ClientService ClientService { get; set; }
    }
}
